version: '3.9'

services:
  app:
    build: .
    container_name: app
    depends_on:
      - db
      - minio
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/app_db
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"

  db:
    image: postgres:17.2-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-09-13T20-26-02Z
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address :9001

  worker:
    build:
      context: .
      dockerfile: Worker.Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  minio_data:
