"""

Revision ID: 1f16f4c3df14
Revises: 9a4ee1821a1b
Create Date: 2025-05-09 16:15:29.559561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f16f4c3df14'
down_revision: Union[str, None] = '9a4ee1821a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_products', sa.Column('minute_count_used', sa.Float(), nullable=False, comment='Использовано минут в месяц', default=0))
    op.alter_column('user_products', 'minute_count',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Использовано минут за все время подписки',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_products', 'minute_count',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Использовано минут за все время подписки',
               existing_nullable=False)
    op.drop_column('user_products', 'minute_count_used')

