"""

Revision ID: 2ca041f95266
Revises: 440f7f70c796
Create Date: 2025-04-22 11:53:38.013414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca041f95266'
down_revision: Union[str, None] = '440f7f70c796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'external_transcation_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Id транзакции в CloudPayments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'external_transcation_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Id транзакции в CloudPayments')
    # ### end Alembic commands ###
