"""

Revision ID: 323ad3c4bd3e
Revises: 85ad22f330a1
Create Date: 2025-04-11 07:46:27.824513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '323ad3c4bd3e'
down_revision: Union[str, None] = '85ad22f330a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_files', 'transcription',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_files', 'transcription',
               existing_type=postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
