"""

Revision ID: 3ecbf9fcf3d9
Revises: 1f16f4c3df14
Create Date: 2025-05-10 14:48:44.272321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ecbf9fcf3d9'
down_revision: Union[str, None] = '1f16f4c3df14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_files', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_files', 'updated_at')
    # ### end Alembic commands ###
