"""

Revision ID: 440f7f70c796
Revises: dccb99e9118e
Create Date: 2025-04-20 21:13:56.734068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440f7f70c796'
down_revision: Union[str, None] = 'dccb99e9118e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_products', sa.Column('product_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'user_products', 'products', ['product_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_products', type_='foreignkey')
    op.drop_column('user_products', 'product_id')
    # ### end Alembic commands ###
