"""

Revision ID: 67d7c990dd55
Revises: 2ca041f95266
Create Date: 2025-04-22 11:54:08.387207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d7c990dd55'
down_revision: Union[str, None] = '2ca041f95266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('external_transaction_id', sa.String(), nullable=True, comment='Id транзакции в CloudPayments'))
    op.drop_column('transactions', 'external_transcation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('external_transcation_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Id транзакции в CloudPayments'))
    op.drop_column('transactions', 'external_transaction_id')
    # ### end Alembic commands ###
