"""

Revision ID: 7a6d1eadcea3
Revises: c2ae2431b1d0
Create Date: 2025-04-18 16:44:25.338053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a6d1eadcea3'
down_revision: Union[str, None] = 'c2ae2431b1d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_files', sa.Column('file_size', sa.Integer(), nullable=True, comment='Размер файла в байтах'))
    op.add_column('user_files', sa.Column('mime_type', sa.String(), nullable=True, comment='MIME-тип файла'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_files', 'mime_type')
    op.drop_column('user_files', 'file_size')
    # ### end Alembic commands ###
