"""Add transcription field to user_files

Revision ID: 85ad22f330a1
Revises: 26fe1154a87a
Create Date: 2025-04-11 07:38:20.497851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ad22f330a1'
down_revision: Union[str, None] = '26fe1154a87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_files', sa.Column('transcription', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_files', 'transcription')
    # ### end Alembic commands ###
