"""

Revision ID: 971fd7ff6178
Revises: bab8b3de6674
Create Date: 2025-04-15 12:58:43.619745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971fd7ff6178'
down_revision: Union[str, None] = 'bab8b3de6674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_products', sa.Column('product_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'user_products', 'products', ['product_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_products', type_='foreignkey')
    op.drop_column('user_products', 'product_id')
    # ### end Alembic commands ###
