"""

Revision ID: 9a4ee1821a1b
Revises: d484a7f73c5d
Create Date: 2025-05-07 15:18:21.708151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4ee1821a1b'
down_revision: Union[str, None] = 'd484a7f73c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_files', sa.Column('transcription_status', sa.String(), nullable=True, comment='Статус расшифровки'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_files', 'transcription_status')
    # ### end Alembic commands ###
