"""

Revision ID: ba41efd048e6
Revises: d1445e249115
Create Date: 2025-04-14 15:35:48.499120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba41efd048e6'
down_revision: Union[str, None] = 'd1445e249115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False, default=True))
    op.add_column('products', sa.Column('sort_order', sa.Integer(), nullable=False, default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sort_order')
    op.drop_column('products', 'is_active')
    # ### end Alembic commands ###
