"""

Revision ID: bab8b3de6674
Revises: bc023be8a4d0
Create Date: 2025-04-15 12:38:59.100767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab8b3de6674'
down_revision: Union[str, None] = 'bc023be8a4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('user_product_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'user_products', ['user_product_id'], ['uuid'])
    op.drop_column('user_products', 'transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_products', sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'user_product_id')
    # ### end Alembic commands ###
