"""

Revision ID: bc023be8a4d0
Revises: ba41efd048e6
Create Date: 2025-04-14 15:47:24.911688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc023be8a4d0'
down_revision: Union[str, None] = 'ba41efd048e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_products', sa.Column('transaction_id', sa.Integer(), nullable=False))
    op.add_column('user_products', sa.Column('amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_products', 'amount')
    op.drop_column('user_products', 'transaction_id')
    # ### end Alembic commands ###
