"""

Revision ID: d1445e249115
Revises: 2024_03_20_insert_base_products
Create Date: 2025-04-13 18:27:53.945949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1445e249115'
down_revision: Union[str, None] = '2024_03_20_insert_base_products'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_files', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_files', 'duration')
    # ### end Alembic commands ###
