"""

Revision ID: dccb99e9118e
Revises: 2024_08_insert_pricing_products
Create Date: 2025-04-20 20:34:15.972452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dccb99e9118e'
down_revision: Union[str, None] = '2024_08_insert_pricing_products'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('external_transcation_id', sa.String(), nullable=False, comment='Id транзакции в CloudPayments'))
    op.add_column('transactions', sa.Column('status', sa.String(), nullable=False, comment='Статус транзакции'))
    op.add_column('user_products', sa.Column('expires_at', sa.DateTime(), nullable=True, comment='Дата окончания подписке'))
    op.add_column('user_products', sa.Column('is_subscription', sa.Boolean(), nullable=False, comment='Является ли записью подписки'))
    op.add_column('user_products', sa.Column('subscription_id', sa.String(), nullable=True, comment='ID подписки в CloudPayments'))
    op.add_column('user_products', sa.Column('interval', sa.String(), nullable=True, comment='Month или Year'))
    op.add_column('user_products', sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли подписка'))
    op.add_column('user_products', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_products', 'updated_at')
    op.drop_column('user_products', 'is_active')
    op.drop_column('user_products', 'interval')
    op.drop_column('user_products', 'subscription_id')
    op.drop_column('user_products', 'is_subscription')
    op.drop_column('user_products', 'expires_at')
    op.drop_column('transactions', 'status')
    op.drop_column('transactions', 'external_transcation_id')
    # ### end Alembic commands ###
