"""

Revision ID: de8aadd5f54d
Revises: 971fd7ff6178
Create Date: 2025-04-15 14:54:33.157073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de8aadd5f54d'
down_revision: Union[str, None] = '971fd7ff6178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_products_to_products',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('user_product', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_product'], ['user_products.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.drop_constraint('user_products_product_id_fkey', 'user_products', type_='foreignkey')
    op.drop_column('user_products', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_products', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_products_product_id_fkey', 'user_products', 'products', ['product_id'], ['uuid'])
    op.drop_table('user_products_to_products')
    # ### end Alembic commands ###
